apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# kubectl apply -k ./
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
namespace: pg18
namePrefix: pg18-
nameSuffix: "-master"
labels:
  - pairs:
      db: postgres
      ver: "18"
      sub: master
    includeSelectors: true
images: # https://hub.docker.com/_/postgres
  - name: postgres
    newTag: "18"
resources:
  - ../../../base18
  - svc.yaml
# patches:
#   - target:
#       kind: Service
#       name: postgres-balancer
#     patch: |
#       - op: replace
#         path: /spec/ports/0/port
#         value: 30117